In [13]:
import numpy as np

In [14]:
row1 = int(input('Enter No of rows for first matrix: '))
col1 = int(input('Enter No of columns for first matrix: '))
row2 = int(input('Enter No of rows for second matrix: '))
col2 = int(input('Enter No of columns for second matrix: '))

Enter No of rows for first matrix: 3
Enter No of columns for first matrix: 2
Enter No of rows for second matrix: 2
Enter No of columns for second matrix: 3


In [15]:
if col1==row2:
    mat1 = []
    for i in range(row1):
        col = []
        for j in range(col1):
            x = int(input(f'Enter the number for a{i+1}.{j+1}: '))
            col.append(x)
        mat1.append(col)
    mat2 = []
    for i in range(row2):
        col = []
        for j in range(col2):
            x = int(input(f'Enter the number for b{i+1}.{j+1}: '))
            col.append(x)
        mat2.append(col)

Enter the number for a1.1: 1
Enter the number for a1.2: 2
Enter the number for a2.1: 3
Enter the number for a2.2: 4
Enter the number for a3.1: 5
Enter the number for a3.2: 6
Enter the number for b1.1: 7
Enter the number for b1.2: 8
Enter the number for b1.3: 9
Enter the number for b2.1: 10
Enter the number for b2.2: 11
Enter the number for b2.3: 12


In [19]:
mat1 = list(np.array(mat1))
mat2 = list(np.array(mat2))

In [ ]:
1 2   7  8  9
3 4   10 11 12
5 6

In [26]:
for row in mat1:
    print(row)
    for i in range(len(mat2)):
        print(mat2[i])
        for j in range(len(mat2[i])):
            print(mat2[i][j])

[1 2]
[7 8 9]
7
8
9
[10 11 12]
10
11
12
[3 4]
[7 8 9]
7
8
9
[10 11 12]
10
11
12
[5 6]
[7 8 9]
7
8
9
[10 11 12]
10
11
12
