In [1]:
import numpy as np

In [153]:
row1 = int(input('Enter No of rows for first matrix: '))
col1 = int(input('Enter No of columns for first matrix: '))
row2 = int(input('Enter No of rows for second matrix: '))
col2 = int(input('Enter No of columns for second matrix: '))

Enter No of rows for first matrix: 4
Enter No of columns for first matrix: 2
Enter No of rows for second matrix: 4
Enter No of columns for second matrix: 1


In [154]:
if col1==row2:
    mat1 = []
    for i in range(row1):
        col = []
        for j in range(col1):
            x = int(input(f'Enter the number for a{i+1}.{j+1}: '))
            col.append(x)
        mat1.append(col)
    mat2 = []
    for i in range(row2):
        col = []
        for j in range(col2):
            x = int(input(f'Enter the number for b{i+1}.{j+1}: '))
            col.append(x)
        mat2.append(col)
else:
    print('Mismatch in matrix dimension')

Mismatch in matrix dimension


In [147]:
final_mat = []
for row_index in range(len(mat1)):
    final_mat.append([])
    row_mul = mat1[row_index]
    for i in range(len(mat2[0])):
        col_mul = []
        for j in mat2:
            col_mul.append(j[i])
        num = 0
        for x in range(len(row_mul)):
            num += row_mul[x]*col_mul[x]
        final_mat[row_index].append(num)
final_mat

[[758], [828], [898], [968]]

In [148]:
final_mat = np.array(final_mat)
# final_mat.shape = (5,5)
final_mat

array([[758],
       [828],
       [898],
       [968]])

In [149]:
mat1_arr = np.array(mat1)
mat2_arr = np.array(mat2)
mat1_arr.dot(mat2_arr)

array([[758],
       [828],
       [898],
       [968]])

In [150]:
mat1_arr,mat2_arr

(array([[21, 22],
        [23, 24],
        [25, 26],
        [27, 28]]),
 array([[12],
        [23]]))

In [155]:
%%HTML
<h1>Abbas</h1>
<h1>Abbas</h1>
<h1>Abbas</h1>
<h1>Abbas</h1>
